// Noirly Calculator — White / Black / Deep Red / Electric Blue

export const lightColors = {
  background:                '#FFFFFF',
  surface:                   '#FFFFFF',
  surfaceDim:                '#f0f0f0',
  surfaceBright:             '#FFFFFF',
  surfaceContainerLowest:    '#FFFFFF',
  surfaceContainerLow:       '#f5f5f5',
  surfaceContainer:          '#eeeeee',
  surfaceContainerHigh:      '#e5e5e5',
  surfaceContainerHighest:   '#d9d9d9',
  surfaceVariant:            '#e5e5e5',
  surfaceTint:               '#3B82F6',
  onSurface:                 '#0B0B0D',
  onSurfaceVariant:          '#333336',
  onBackground:              '#0B0B0D',
  inverseSurface:            '#0B0B0D',
  inverseOnSurface:          '#FFFFFF',
  outline:                   '#aaaaaa',
  outlineVariant:            '#cccccc',
  primary:                   '#3B82F6',
  onPrimary:                 '#FFFFFF',
  primaryContainer:          '#3B82F6',
  onPrimaryContainer:        '#FFFFFF',
  inversePrimary:            '#1d4ed8',
  primaryFixed:              '#93c5fd',
  primaryFixedDim:           '#3B82F6',
  onPrimaryFixed:            '#FFFFFF',
  onPrimaryFixedVariant:     '#1d4ed8',
  secondary:                 '#B11226',
  onSecondary:               '#FFFFFF',
  secondaryContainer:        '#f5c6cb',
  onSecondaryContainer:      '#B11226',
  secondaryFixed:            '#f87171',
  secondaryFixedDim:         '#B11226',
  onSecondaryFixed:          '#FFFFFF',
  onSecondaryFixedVariant:   '#7a0d1a',
  tertiary:                  '#0B0B0D',
  onTertiary:                '#FFFFFF',
  tertiaryContainer:         '#e5e5e5',
  onTertiaryContainer:       '#0B0B0D',
  tertiaryFixed:             '#0B0B0D',
  tertiaryFixedDim:          '#333336',
  onTertiaryFixed:           '#FFFFFF',
  onTertiaryFixedVariant:    '#aaaaaa',
  error:                     '#B11226',
  onError:                   '#FFFFFF',
  errorContainer:            '#f5c6cb',
  onErrorContainer:          '#B11226',
} as const;

export const darkColors = {
  background:                '#0F0F11',
  surface:                   '#0F0F11',
  surfaceDim:                '#0a0a0c',
  surfaceBright:             '#1c1c1f',
  surfaceContainerLowest:    '#0a0a0c',
  surfaceContainerLow:       '#141417',
  surfaceContainer:          '#1a1a1e',
  surfaceContainerHigh:      '#222227',
  surfaceContainerHighest:   '#2c2c32',
  surfaceVariant:            '#222227',
  surfaceTint:               '#60a5fa',
  onSurface:                 '#F0F0F2',
  onSurfaceVariant:          '#B0B0B8',
  onBackground:              '#F0F0F2',
  inverseSurface:            '#F0F0F2',
  inverseOnSurface:          '#0F0F11',
  outline:                   '#555560',
  outlineVariant:            '#333340',
  primary:                   '#60a5fa',
  onPrimary:                 '#FFFFFF',
  primaryContainer:          '#2563eb',
  onPrimaryContainer:        '#FFFFFF',
  inversePrimary:            '#93c5fd',
  primaryFixed:              '#1d4ed8',
  primaryFixedDim:           '#60a5fa',
  onPrimaryFixed:            '#FFFFFF',
  onPrimaryFixedVariant:     '#93c5fd',
  secondary:                 '#B11226',
  onSecondary:               '#FFFFFF',
  secondaryContainer:        '#4a0a13',
  onSecondaryContainer:      '#f87171',
  secondaryFixed:            '#f87171',
  secondaryFixedDim:         '#B11226',
  onSecondaryFixed:          '#FFFFFF',
  onSecondaryFixedVariant:   '#f87171',
  tertiary:                  '#F0F0F2',
  onTertiary:                '#0F0F11',
  tertiaryContainer:         '#2c2c32',
  onTertiaryContainer:       '#F0F0F2',
  tertiaryFixed:             '#F0F0F2',
  tertiaryFixedDim:          '#B0B0B8',
  onTertiaryFixed:           '#0F0F11',
  onTertiaryFixedVariant:    '#555560',
  error:                     '#f87171',
  onError:                   '#FFFFFF',
  errorContainer:            '#4a0a13',
  onErrorContainer:          '#f87171',
} as const;

export type Colors = Record<keyof typeof lightColors, string>;

// Default export (light) kept for backward compatibility during migration
const colors: Colors = lightColors;
export default colors;

